### ISSUE TITLE
first/last parameters for [person]

### ISSUE THREAD

**Issue by si-kotic** [dfinke/NameIT#16]
Excellent module!  Very useful.

You should consider adding 'first' and 'last' as parameters for 'person' in the same way that you have 'male' and 'female'.

**Comment by dfinke** [comment]
What to try and change that? Do a PR?

**Comment by dfinke** [comment]
Added. https://github.com/dfinke/NameIT/commit/0380961650d7413531ffda1320959917d469b1f0

**Comment by si-kotic** [comment]
Thank you, that's really helpful!

**Comment by dfinke** [comment]
Thanks for the suggestion
