### ISSUE TITLE
New-NameItTemplate is not found in module

### ISSUE THREAD

**Issue by NakedPowerShell** [dfinke/NameIT#21]
In the **readme.md** you have several examples of **New-NameItTemplate** and the function is not found in the module.

**Comment by NakedPowerShell** [comment]
Correction:  I found the function in the code, but it does not work.

`Invoke-Generate (New-NameItTemplate {[PSCustomObject]@{Company="";Name=""}}) -Count 5 -AsPSObject
`

Results:

```
Invoke-Generate (New-NameItTemplate {[PSCustomObject]@{Company="";Name=""}}) -Count 5 -AsPSObject
New-NameItTemplate : The term 'New-NameItTemplate' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:18
+ Invoke-Generate (New-NameItTemplate {[PSCustomObject]@{Company="";Nam ...
+                  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-NameItTemplate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by dfinke** [comment]
What version of NameIT do you have?

![image](https://user-images.githubusercontent.com/67258/55524382-2ab49080-565b-11e9-8075-9a30e829e91f.png)

**Comment by briantist** [comment]
The file required for this to work was deleted in 83160fc5316fd2f8f8a742783bc7354ee294cea0 .
This will be restored in #26
