### ISSUE TITLE
ig "[noun] [randomdate]" fails with: Cannot validate argument on parameter 'Name'. The argument is null or empty

### ISSUE THREAD

**Issue by jpoehls** [dfinke/NameIT#27]
## Steps

* NameIT module version 2.1.0
* Run `NameIT\Invoke-Generate "[noun] [randomdate]" -Count 1`

## Result

```
Test-GeneratorInSet : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Users\jpoehls\Documents\PowerShell\Modules\nameit\2.1.0\Public\Invoke-Generate.ps1:126 char:47
+                 if (Test-GeneratorInSet -Name $fn) {
+                                               ~~~
+ CategoryInfo          : InvalidData: (:) [Test-GeneratorInSet], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Test-GeneratorInSet
```

## $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Notes

Possibly related to the custom date format I have set in Windows? `yyyy-MM-dd`

For example, `ig "[randomdate]` returns `0183-11-22`.

**Comment by dfinke** [comment]
cc: @briantist - thoughts?

**Comment by briantist** [comment]
Shouldn't be related to your custom date format at all. I would guess that it's because of the literal space. If you did `ig "[name][space][randomdate]" -Count 1` then it would work. 

I can't test it until I return home from traveling. Let me know if that works. 

In any case it's a bug. Most likely we just have to remove the validation on the `-Name` parameter of `Test-GeneratorInSet`, or possibly make it accept whitespace but not nulls.

**Comment by dfinke** [comment]
Yup, that works. Whenever it works for you, let's pair program on this.

**Comment by jpoehls** [comment]
> Shouldn't be related to your custom date format at all. I would guess that it's because of the literal space. If you did `ig "[name][space][randomdate]" -Count 1` then it would work.

Yep, that works for me. 

FWIW this isn't urgent or a blocker for me. Just something I noticed while playing around. Very cool module!

**Comment by dfinke** [comment]
Thanks for reporting it, it's a bug. A bunch of refactoring was done. Always good to catch this in the wild and make the module more robust.

**Comment by just-denis** [comment]
Hello, I had this issue when parsing a multi-line file and feeding strings line by line into ig - resolved by explicitly adding "`n" to the end of each string before passing to ig.

**Comment by briantist** [comment]
@just-denis that's interesting, could you give some example invocations that did and didn't work? Maybe I can address it in the same fix.
