### ISSUE TITLE
 Invoke-Generate '[person]' getting blank output

### ISSUE THREAD

**Issue by rom3029** [dfinke/NameIT#34]
Hello,

Thanks for developping this script.

I tried the Invoke-Generate '[person]' , with or without quotes, also tried '[person male first]' and others.

I get a blank output for these, tough the other options work fine. I use powershell 5.1.18362.752

I'll get a look at the code and update you if I find out why i get an issue.

Best regards,

**Comment by dfinke** [comment]
Let me know.

I'm running PS v5.1 

![image](https://user-images.githubusercontent.com/67258/88977928-c0caec00-d28c-11ea-8851-f248f41fd8b3.png)

**Comment by Zergie** [comment]
Hey there,

i get pretty much the same issue. Running on Powershell 7.1 but get the same behaviour in Powershell 5.1.19041.610

![1](https://user-images.githubusercontent.com/9965972/100727500-a170d680-33c6-11eb-82fc-7d37b4894da6.png)

It seams that '[person]' is affected..
